name: WorkflowA

on: push
jobs:
    prettify:
        runs-on: ubuntu-latest
        steps:
          - name: Siapkan file dari repo
            uses: actions/checkout@v2
          - name: set up node js
            uses: actions/setup-node@v2.1.5
          - name: siapkan dependansi npm
            uses: npm install
          - name: format file kode repo
            uses: npm run prettify
          - name: Push kembali perubahan yang telah dilakukan
            run: |
                git config user.name ‘Nama Bot’
                # Email bebas tetapi valid
                git config user.email ‘181sag@gmail.com’
                # Tambahkan semua file yang berubah
                git add --all
                # Judul commit yang diinginkan
                git commit -m ‘Automatic code format’
                # Lakukan push
                git push
